const aiResponses = [
  "Olá! Como posso ajudar você hoje?",
  "Claro! Aqui está a informação que você pediu.",
  "**Dica:** Você pode usar comandos para gerar camadas no mapa.",
  "Aqui está um exemplo:\n\n- Item 1\n- Item 2\n- Item 3",
  "Posso centralizar a visualização nesses pontos para você?",
  "Ótima escolha! O que mais deseja explorar?",
  "Para mais detalhes, acesse [nosso site](https://example.com).",
  "Camada adicionada com sucesso!",
  "Você pode digitar outra área ou comando.",
  "_Processando sua solicitação..._",
  "Encontrei 1472 academias e já adicionei como uma nova camada no mapa.",
  "**Atenção:** Alguns dados podem estar desatualizados.",
  "Aqui está um resumo:\n\n1. Passo um\n2. Passo dois\n3. Passo três",
  "Visualização centralizada!",
  "Você gostaria de salvar esta camada?",
  "Dados atualizados com sucesso.",
  "_Nenhum resultado encontrado para sua busca._",
  "Você pode tentar um comando diferente.",
  "**Sugestão:** Use /restaurantes para ver opções próximas.",
  "Mapa atualizado!",
  "Aqui estão os resultados:\n\n- Academia X\n- Academia Y",
  "Posso ajudar com mais alguma coisa?",
  "**Nota:** O sistema está em modo beta.",
  "Digite um novo comando para continuar.",
  "_Carregando informações..._",
  "Camada removida com sucesso.",
  "Você pode compartilhar este mapa com outros usuários.",
  "**Dica:** Use /parques para ver áreas verdes.",
  "Aqui está o que encontrei:\n\n- Opção 1\n- Opção 2\n- Opção 3\n- Opção 4",
  "Visualização ajustada conforme solicitado.",
  "_Processando..._",
  "Dados salvos!",
  "**Atenção:** Limite de camadas atingido.",
  "Você pode remover camadas antigas para adicionar novas.",
  "Aqui está um tutorial rápido:\n\n1. Clique em 'Adicionar'\n2. Escolha a área\n3. Confirme",
  "Mapa limpo!",
  "**Sugestão:** Experimente o modo noturno.",
  "_Buscando informações adicionais..._",
  "Camada personalizada criada.",
  "Você pode editar esta camada a qualquer momento.",
  "**Nota:** Algumas funções estão indisponíveis no momento.",
  "Digite /ajuda para ver todos os comandos.",
  "Aqui estão as opções disponíveis:",
  "- Visualizar\n- Editar\n- Remover",
  "_Aguarde enquanto processamos sua solicitação..._",
  "Camada duplicada detectada.",
  "Você pode renomear esta camada.",
  "**Dica:** Use filtros para refinar sua busca.",
  "Aqui está um exemplo de comando:\n\n`/academias zona sul`",
  "Visualização restaurada ao padrão.",
  "_Sincronizando dados..._",
  "Camada compartilhada com sucesso.",
  "Você pode exportar os dados em CSV.",
  "**Nota:** Resultados limitados a 100 itens.",
  "Digite /voltar para desfazer a última ação.",
  "_Atualizando visualização..._",
  "Camada bloqueada para edição.",
  "Você pode desbloquear nas configurações.",
  "**Sugestão:** Use /escolas para ver instituições próximas.",
  "Aqui está a lista solicitada:\n\n- Item A\n- Item B\n- Item C",
  "Visualização salva!",
  "_Aguardando novo comando..._",
  "Camada renomeada com sucesso.",
  "Você pode adicionar notas a esta camada.",
  "**Nota:** Dados sujeitos a alterações.",
  "Digite /sair para encerrar a sessão.",
  "_Verificando permissões..._",
  "Camada protegida por senha.",
  "Você pode alterar a senha nas configurações.",
  "**Dica:** Use /hospitais para ver unidades de saúde.",
  "Aqui está um resumo dos dados:\n\n- Total: 100\n- Novos: 10\n- Removidos: 2",
  "Visualização expandida!",
  "_Sincronização concluída._",
  "Camada favoritada.",
  "Você pode desfavoritar a qualquer momento.",
  "**Nota:** Limite de visualizações atingido.",
  "Digite /resetar para restaurar padrões.",
  "_Buscando localização atual..._",
  "Camada movida para o topo.",
  "Você pode reorganizar as camadas.",
  "**Sugestão:** Use /transporte para ver linhas próximas.",
  "Aqui está o histórico:\n\n- Ação 1\n- Ação 2\n- Ação 3",
  "Visualização reduzida.",
  "_Aguardando interação do usuário..._",
  "Camada restaurada.",
  "Você pode restaurar camadas removidas.",
  "**Nota:** Dados sincronizados automaticamente.",
  "Digite /config para acessar configurações.",
  "_Atualizando camada..._",
  "Camada oculta.",
  "Você pode exibir camadas ocultas nas opções.",
  "**Dica:** Use /eventos para ver o que está acontecendo na região.",
  "Aqui está a configuração atual:\n\n- Opção A\n- Opção B",
  "Visualização personalizada aplicada.",
  "_Aguardando próxima ação..._",
  "Camada removida da visualização.",
  "Você pode adicionar novamente se desejar.",
  "**Nota:** Algumas camadas são exclusivas para administradores.",
  "Digite /admin para acessar funções avançadas."
];

export default aiResponses; 